[package]
name = "webrtc"
version = "0.4.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of WebRTC API"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/webrtc"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/webrtc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-util", version = "0.5.3" }
sdp = "0.5.1"
mdns = { package = "webrtc-mdns", version = "0.4.2" }
stun = "0.4.2"
turn = "0.5.3"
ice = { package = "webrtc-ice", version = "0.6.4" }
dtls = { package = "webrtc-dtls", version = "0.5.2" }
rtp = "0.6.5"
rtcp = "0.6.5"
srtp = { package = "webrtc-srtp", version = "0.8.9" }
sctp = { package = "webrtc-sctp", version = "0.4.3" }
data = { package = "webrtc-data", version = "0.3.3" }
media = { package = "webrtc-media", version = "0.4.5" }
interceptor = "0.7.6"
tokio = { version = "1.15.0", features = ["full"] }
log = "0.4.14"
async-trait = "0.1.52"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
rand = "0.8.4"
bytes = "1.1.0"
thiserror = "1.0.30"
waitgroup = "0.1.2"
regex = "1.5.4"
url = "2.2.2"
rustls = { version = "0.19.0", features = ["dangerous_configuration"]}
rcgen = { version = "0.8.14", features = ["pem", "x509-parser"]}
ring = "0.16.20"
sha2 = "0.10.1"
lazy_static = "1.4.0"
hex = "0.4.3"

[dev-dependencies]
tokio-test = "0.4.2"
env_logger = "0.9.0"

[profile.dev]
opt-level = 0
