[package]
name = "webrtc-rs"
version = "0.0.1"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"
description = "A pure Rust implementation of WebRTC API"
license = "MIT"
documentation = "https://docs.rs/webrtc-rs"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/webrtc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0.1", features = ["full"] }
rand = { version = "0.8.1" }
