[package]
name = "webrtc"
version = "0.2.2"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of WebRTC API"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/webrtc"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/webrtc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-util", version = "0.5.1" }
sdp = "0.4.0"
mdns = { package = "webrtc-mdns", version = "0.4.0" }
stun = "0.4.0"
turn = "0.5.1"
ice = { package = "webrtc-ice", version = "0.5.1" }
dtls = { package = "webrtc-dtls", version = "0.5.0" }
rtp = "0.6.1"
rtcp = "0.6.1"
srtp = { package = "webrtc-srtp", version = "0.8.3" }
sctp = { package = "webrtc-sctp", version = "0.4.1" }
data = { package = "webrtc-data", version = "0.3.1" }
media = { package = "webrtc-media", version = "0.4.1" }
interceptor = "0.6.4"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4.14"
async-trait = "0.1.42"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
bytes = "1"
thiserror = "1.0"
waitgroup = "0.1.2"
regex = "1"
url = "2.2.2"
rustls = { version = "0.19.0", features = ["dangerous_configuration"]}
rcgen = { version = "0.8.13", features = ["pem", "x509-parser"]}
ring = "0.16.19"
sha2 = "0.9.1"
lazy_static = "1.4"
hex = "0.4.3"

[dev-dependencies]
tokio-test = "0.4"
env_logger = "0.9.0"
# chrono = "0.4.19"

[profile.dev]
opt-level = 0
