[package]
name = "signal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
anyhow = "1.0.44"
base64 = "0.13.0"
lazy_static = "1.4"
hyper = { version = "0.14.13", features = ["full"] }