[package]
name = "webrtc"
version = "0.6.1"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2021"
description = "A pure Rust implementation of WebRTC API"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/webrtc"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/webrtc"
readme = "../README.md"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data = { version = "0.6.0", path = "../data", package = "webrtc-data" }
dtls = { version = "0.7.0", path = "../dtls", package = "webrtc-dtls" }
ice = { version = "0.9.0", path = "../ice", package = "webrtc-ice" }
interceptor = { version = "0.8.2", path = "../interceptor" }
mdns = { version = "0.5.0", path = "../mdns", package = "webrtc-mdns" }
media = { version = "0.5.0", path = "../media", package = "webrtc-media" }
rtcp = { version = "0.7.0", path = "../rtcp" }
rtp = { version = "0.6.7", path = "../rtp" }
sctp = { version = "0.7.0", path = "../sctp", package = "webrtc-sctp" }
sdp = { version = "0.5.2", path = "../sdp" }
srtp = { version = "0.9.0", path = "../srtp", package = "webrtc-srtp" }
stun = { version = "0.4.3", path = "../stun" }
turn = { version = "0.6.0", path = "../turn" }
util = { version = "0.7.0", path = "../util", package = "webrtc-util" }

arc-swap = "1.5"
tokio = { version = "1.19", features = ["full"] }
log = "0.4.16"
async-trait = "0.1.56"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
bytes = "1"
thiserror = "1.0"
waitgroup = "0.1.2"
regex = "1"
url = "2.2"
rustls = { version = "0.19.0", features = ["dangerous_configuration"]}
rcgen = { version = "0.9.2", features = ["pem", "x509-parser"]}
ring = "0.16.20"
sha2 = "0.10.6"
lazy_static = "1.4"
hex = "0.4.3"
pem = { version = "1", optional = true }

# [minimal-versions]
# fixes "the trait bound `time::Month: From<u8>` is not satisfied"
# https://github.com/est31/rcgen/pull/88
# Version 0.3.14 requires Rust 1.59.0 which we don't currently support
time = "~0.3.1"

[dev-dependencies]
tokio-test = "0.4.0" # must match the min version of the `tokio` crate above
env_logger = "0.9.0"

[features]
pem = ["dep:pem", "dtls/pem"]
