[package]
name = "webrtc-srtp"
version = "0.8.9"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of SRTP"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/webrtc-srtp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/srtp"

[dependencies]
util = { path = "../util", package = "webrtc-util", default-features = false, features = [
    "conn",
    "buffer",
    "marshal",
] }
rtp = { path = "../rtp" }
rtcp = { path = "../rtcp" }

byteorder = "1.4.3"
bytes = "1.1.0"
thiserror = "1.0.30"
hmac = { version = "0.11.0", features = ["std"] }
sha-1 = "0.9.8"
ctr = "0.8.0"
aes = "0.7.5"
subtle = "2.4.1"
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1.52"
log = "0.4.14"
aead = { version = "0.4.3", features = ["std"] }
aes-gcm = "0.9.4"

[dev-dependencies]
tokio-test = "0.4.2"
lazy_static = "1.4.0"
