[package]
name = "sdp"
version = "0.3.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of SDP"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/sdp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/sdp"

[dependencies]
url = "2.2.2"
rand = "0.8.4"
thiserror = "1.0"
substring = "1.4.5"
