[package]
name = "turn"
version = "0.1.0"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
binaries = ["clap"]
default = ["binaries"]

[dependencies]
util = { git = "https://github.com/webrtc-rs/util", branch = "main" }
stun = { git = "https://github.com/webrtc-rs/stun", branch = "main" }
lazy_static = "1.3.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
clap = { version = "2", optional = true, default-features = false }


[dev-dependencies]
tokio-test = "0.4"


[[example]]
name = "turn_client_udp"
path = "examples/turn_client_udp.rs"
required-features = ["binaries"]
bench = false