[package]
name = "webrtc-rtp"
version = "0.1.1"
authors = ["Rain Liu <yliu@webrtc.rs>", "Michael Uti <utimichael9@gmail.com>"]
edition = "2018"
description = "A pure Rust implementation of RTP"
license = "MIT"
documentation = "https://docs.rs/webrtc-rtp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/rtp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
rand = "0.8.0"
thiserror = "1"

[dev-dependencies]
chrono = "0.4.7"
criterion = "0.3"

[[bench]]
name = "packet_bench"
harness = false
