[package]
name = "hub"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../../../util", package = "webrtc-util", default-features = false, features = [
    "conn"
] }
dtls = { package = "webrtc-dtls", path = "../../" }

tokio = { version = "1.32.0", features = ["full"] }
rcgen = { version = "0.11", features = ["pem", "x509-parser"] }
rustls = "0.21"
rustls-pemfile = "1"
thiserror = "1"
