[package]
name = "turn"
version = "0.6.1"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2021"
description = "A pure Rust implementation of TURN"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/turn"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/turn"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
util = { version = "0.7.0", path = "../util", package = "webrtc-util", default-features = false, features = ["conn", "vnet"] }
stun = { version = "0.4.3", path = "../stun" }

tokio = { version = "1.19", features = ["full"] }
async-trait = "0.1.56"
log = "0.4.16"
base64 = "0.13.0"
rand = "0.8.5"
ring = "0.16.20"
md-5 = "0.10.1"
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4.0" # must match the min version of the `tokio` crate above
env_logger = "0.9.0"
chrono = "0.4.23"
hex = "0.4.3"
clap = "3.2.6"
criterion = "0.3.5"

[features]
metrics = []

[[bench]]
name = "bench"
harness = false

[[example]]
name = "turn_client_udp"
path = "examples/turn_client_udp.rs"
bench = false

[[example]]
name = "turn_server_udp"
path = "examples/turn_server_udp.rs"
bench = false
