[package]
name = "webrtc-sctp"
version = "0.7.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2021"
description = "A pure Rust implementation of SCTP"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/webrtc-sctp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/sctp"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { version = "0.7.0", path = "../util", package = "webrtc-util", default-features = false, features = ["conn"] }

arc-swap = "1.5"
tokio = { version = "1.19", features = ["full"] }
bytes = "1"
rand = "0.8.5"
crc = "3.0"
async-trait = "0.1.56"
log = "0.4.16"
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4.0" # must match the min version of the `tokio` crate above
lazy_static = "1.4.0"
env_logger = "0.9.0"
chrono = "0.4.23"
clap = "3.2.6"

[[example]]
name = "ping"
path = "examples/ping.rs"
bench = false

[[example]]
name = "pong"
path = "examples/pong.rs"
bench = false
